/* (c) 2023  Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 *
 * Original from GeoFence 3.6 under GPL 2.0 license
 */

package org.geoserver.acl.domain.adminrules;

import lombok.Builder;
import lombok.With;
import org.jspecify.annotations.Nullable;

/**
 * Workspace administration privilege rule.
 *
 * <p>Controls who can manage GeoServer workspaces (configure, modify, or delete workspace resources).
 * Unlike {@link org.geoserver.acl.domain.rules.Rule} which controls data access, AdminRule controls
 * workspace administration.
 *
 * <p>AdminRules are evaluated in priority order (lower numbers first). The first matching rule
 * determines whether the user has admin access.
 *
 * <p>Comparison with Rule:
 * <table border="1">
 * <tr><th>Aspect</th><th>AdminRule</th><th>Rule</th></tr>
 * <tr><td>Purpose</td><td>Workspace management</td><td>Data access</td></tr>
 * <tr><td>Grant Types</td><td>ADMIN, USER</td><td>ALLOW, DENY, LIMIT</td></tr>
 * <tr><td>Matching</td><td>user, role, IP, workspace</td><td>+ service, request, layer</td></tr>
 * </table>
 *
 * <p>Examples:
 * <pre>{@code
 * // Grant admin access to workspace "topp" for user "alice"
 * AdminRule adminRule = AdminRule.admin()
 *     .withUsername("alice")
 *     .withWorkspace("topp")
 *     .withPriority(100);
 *
 * // Restrict workspace admin to internal network
 * AdminRule restrictedAdmin = AdminRule.admin()
 *     .withRolename("ROLE_WORKSPACE_ADMIN")
 *     .withWorkspace("sensitive")
 *     .withAddressRange("192.168.1.0/24")
 *     .withPriority(50);
 * }</pre>
 *
 * <p>All properties are immutable. Use {@code with*()} methods or {@code toBuilder()} to create
 * modified copies.
 *
 * @param id unique internal identifier, generated by repository. Can be {@code null} for unsaved
 *     rules.
 * @param extId external identifier for integration with other systems.
 * @param name human-readable name (optional).
 * @param description description (optional).
 * @param priority priority determines evaluation order (lower = higher priority). Must be unique.
 * @param identifier matching criteria (username, role, IP address, workspace).
 * @param access grant type (ADMIN or USER).
 * @since 1.0
 * @see AdminRuleIdentifier
 * @see AdminGrantType
 * @see org.geoserver.acl.domain.rules.Rule
 * @author Emanuele Tajariol (etj at geo-solutions.it) (originally as part of GeoFence)
 * @author Gabriel Roldan (adapted to GeoServer ACL)
 */
@With
@Builder(toBuilder = true, builderClassName = "Builder")
public record AdminRule(
        @Nullable String id,
        @Nullable String extId,
        @Nullable String name,
        @Nullable String description,
        long priority,
        AdminRuleIdentifier identifier,
        @Nullable AdminGrantType access) {

    private static final AdminRuleIdentifier EMPTY_IDENTIFIER =
            AdminRuleIdentifier.builder().build();

    public AdminRule {
        if (identifier == null) identifier = EMPTY_IDENTIFIER;
    }

    @Override
    public String toString() {
        return "AdminRule[id: %s, %s]".formatted(id, toShortString());
    }

    public boolean isAdmin() {
        return access == AdminGrantType.ADMIN;
    }

    public AdminRule withUsername(String username) {
        return withIdentifier(identifier.withUsername(username));
    }

    public AdminRule withRolename(String rolename) {
        return withIdentifier(identifier.withRolename(rolename));
    }

    public AdminRule withWorkspace(String workspace) {
        return withIdentifier(identifier.withWorkspace(workspace));
    }

    public AdminRule withAddressRange(String addressRange) {
        return withIdentifier(identifier.withAddressRange(addressRange));
    }

    public static AdminRule user() {
        return AdminRule.builder().access(AdminGrantType.USER).build();
    }

    public static AdminRule admin() {
        return AdminRule.builder().access(AdminGrantType.ADMIN).build();
    }

    public String toShortString() {
        return "priority: %d, access: %s, %s".formatted(priority, access, identifier.toShortString());
    }
}
