version: "3.1"

volumes:
  acl_data:

services:
  acldb:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=acl
      - POSTGRES_USER=acl
      - POSTGRES_PASSWORD=acls3cr3t
    volumes:
      - acl_data:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
    ports:
      - 6432:5432

  acl:
    image: geoservercloud/geoserver-acl:1.2.0
    volumes:
      - ./docker-compose-acl-config.yml:/opt/app/bin/acl.yml
    ports:
      - 9000:8080
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G

