

jndi:
  datasources:
    acl:
      enabled: true
      wait-for-it: true
      wait-timeout: 15
      url: jdbc:postgresql://acldb:5432/acl
      username: acl
      password: acls3cr3t
      maximum-pool-size: 50
      minimum-idle: 2
      connection-timeout: 3000
      idle-timeout: 60000

acl:
  db:
    jndiName: java:comp/env/jdbc/acl
    hbm2ddl.auto: update
    schema: acl

logging:
  level:
    root: warn
    org.geoserver.acl: info
    org.geoserver.cloud.config: info
    org.springframework.jdbc.support: info

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
