/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.geoserver.acl.webapi.v1.server;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Set;
import org.geoserver.acl.webapi.v1.model.InsertPosition;
import org.geoserver.acl.webapi.v1.model.LayerDetails;
import org.geoserver.acl.webapi.v1.model.Rule;
import org.geoserver.acl.webapi.v1.model.RuleFilter;
import org.geoserver.acl.webapi.v1.model.RuleLimits;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2026-01-29T18:51:14.805992-03:00[America/Argentina/Cordoba]",
        comments = "Generator version: 7.17.0")
@Validated
@Tag(
        name = "DataRules",
        description =
                "Manage data access rules that control permissions for GeoServer layers, workspaces, and OWS services. Rules can grant access (ALLOW), deny access (DENY), or impose restrictions (LIMIT) on resources. ")
public interface DataRulesApi {

    default DataRulesApiDelegate getDelegate() {
        return new DataRulesApiDelegate() {};
    }

    String PATH_COUNT_ALL_RULES = "/rules/query/count";
    /**
     * GET /rules/query/count : Count all data rules
     * Returns the total number of data access rules currently configured in the system.
     *
     * @return The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used.  (status code 200)
     */
    @Operation(
            operationId = "countAllRules",
            summary = "Count all data rules",
            description = "Returns the total number of data access rules currently configured in the system. ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = DataRulesApi.PATH_COUNT_ALL_RULES,
            produces = {"application/json"})
    default ResponseEntity<Integer> countAllRules() {

        return getDelegate().countAllRules();
    }

    String PATH_COUNT_RULES = "/rules/query/count";
    /**
     * POST /rules/query/count : Count rules matching filter criteria
     * Returns the number of data rules that match the provided filter criteria. Useful for determining result set size before paginating through query results.
     *
     * @param ruleFilter  (required)
     * @return The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used.  (status code 200)
     */
    @Operation(
            operationId = "countRules",
            summary = "Count rules matching filter criteria",
            description =
                    "Returns the number of data rules that match the provided filter criteria. Useful for determining result set size before paginating through query results. ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = DataRulesApi.PATH_COUNT_RULES,
            produces = {"application/json"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Integer> countRules(
            @Parameter(name = "RuleFilter", description = "", required = true) @Valid @RequestBody
                    RuleFilter ruleFilter) {
        return getDelegate().countRules(ruleFilter);
    }

    String PATH_CREATE_RULE = "/rules";
    /**
     * POST /rules : Create a new data rule
     * Creates a new data access rule. The rule will be inserted at the specified priority position. If a rule with the same identifier (same combination of user, role, service, request, workspace, layer, etc.) already exists, the operation will fail with a 409 Conflict.  The priority determines evaluation order - lower numbers are evaluated first. Use the position parameter to control how the priority value is interpreted (fixed value, from start, or from end of the list).
     *
     * @param rule  (required)
     * @param position Controls how the rule&#39;s priority value should be interpreted when inserting a new rule. See the InsertPosition schema for detailed explanation of FIXED, FROM_START, and FROM_END options. Defaults to FIXED if not specified.  (optional)
     * @return A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID.  (status code 201)
     *         or Invalid request. Common causes include: - Providing a rule with a non-null id (id is auto-generated) - Invalid field values or combinations  (status code 400)
     *         or A rule with the same identifier already exists. Rules are uniquely identified by the combination of: user, role, service, request, subfield, workspace, layer, and addressRange. If you need to modify an existing rule, use the PATCH endpoint instead.  (status code 409)
     */
    @Operation(
            operationId = "createRule",
            summary = "Create a new data rule",
            description =
                    "Creates a new data access rule. The rule will be inserted at the specified priority position. If a rule with the same identifier (same combination of user, role, service, request, workspace, layer, etc.) already exists, the operation will fail with a 409 Conflict.  The priority determines evaluation order - lower numbers are evaluated first. Use the position parameter to control how the priority value is interpreted (fixed value, from start, or from end of the list). ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "201",
                        description =
                                "A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Rule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = Rule.class))
                        }),
                @ApiResponse(
                        responseCode = "400",
                        description =
                                "Invalid request. Common causes include: - Providing a rule with a non-null id (id is auto-generated) - Invalid field values or combinations "),
                @ApiResponse(
                        responseCode = "409",
                        description =
                                "A rule with the same identifier already exists. Rules are uniquely identified by the combination of: user, role, service, request, subfield, workspace, layer, and addressRange. If you need to modify an existing rule, use the PATCH endpoint instead. ")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = DataRulesApi.PATH_CREATE_RULE,
            produces = {"application/json", "application/x-jackson-smile"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Rule> createRule(
            @Parameter(name = "Rule", description = "", required = true) @Valid @RequestBody Rule rule,
            @Parameter(
                            name = "position",
                            description =
                                    "Controls how the rule's priority value should be interpreted when inserting a new rule. See the InsertPosition schema for detailed explanation of FIXED, FROM_START, and FROM_END options. Defaults to FIXED if not specified. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "position", required = false)
                    @Nullable
                    InsertPosition position) {
        return getDelegate().createRule(rule, position);
    }

    String PATH_DELETE_ALL_RULES = "/rules";
    /**
     * DELETE /rules : Delete all data rules
     * Removes all data access rules from the system. This operation is atomic - either all rules are deleted successfully, or none are deleted. Returns the count of rules that were removed. Use with caution as this operation cannot be undone.
     *
     * @return The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used.  (status code 200)
     */
    @Operation(
            operationId = "deleteAllRules",
            summary = "Delete all data rules",
            description =
                    "Removes all data access rules from the system. This operation is atomic - either all rules are deleted successfully, or none are deleted. Returns the count of rules that were removed. Use with caution as this operation cannot be undone. ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = DataRulesApi.PATH_DELETE_ALL_RULES,
            produces = {"application/json"})
    default ResponseEntity<Integer> deleteAllRules() {

        return getDelegate().deleteAllRules();
    }

    String PATH_DELETE_RULE_BY_ID = "/rules/id/{id}";
    /**
     * DELETE /rules/id/{id} : Delete a data rule
     * Permanently removes the specified data rule from the system.
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @return Rule successfully deleted (status code 200)
     *         or No rule exists with the specified ID (status code 404)
     */
    @Operation(
            operationId = "deleteRuleById",
            summary = "Delete a data rule",
            description = "Permanently removes the specified data rule from the system.",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(responseCode = "200", description = "Rule successfully deleted"),
                @ApiResponse(responseCode = "404", description = "No rule exists with the specified ID")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(method = RequestMethod.DELETE, value = DataRulesApi.PATH_DELETE_RULE_BY_ID)
    default ResponseEntity<Void> deleteRuleById(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id) {
        return getDelegate().deleteRuleById(id);
    }

    String PATH_FIND_ONE_RULE_BY_PRIORITY = "/rules/query/one/priority/{priority}";
    /**
     * GET /rules/query/one/priority/{priority} : Find rule by priority value
     * Retrieves the data rule with the specified priority value. If multiple rules somehow have the same priority (which shouldn&#39;t normally occur), returns a 409 Conflict error.
     *
     * @param priority The rule priority to search for (required)
     * @return A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID.  (status code 200)
     *         or Not found (status code 404)
     *         or Conflict, there&#39;s more than one rule with the requested priority (status code 409)
     */
    @Operation(
            operationId = "findOneRuleByPriority",
            summary = "Find rule by priority value",
            description =
                    "Retrieves the data rule with the specified priority value. If multiple rules somehow have the same priority (which shouldn't normally occur), returns a 409 Conflict error. ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Rule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = Rule.class))
                        }),
                @ApiResponse(responseCode = "404", description = "Not found"),
                @ApiResponse(
                        responseCode = "409",
                        description = "Conflict, there's more than one rule with the requested priority")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = DataRulesApi.PATH_FIND_ONE_RULE_BY_PRIORITY,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Rule> findOneRuleByPriority(
            @NotNull
                    @Parameter(
                            name = "priority",
                            description = "The rule priority to search for",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("priority")
                    Long priority) {
        return getDelegate().findOneRuleByPriority(priority);
    }

    String PATH_GET_LAYER_DETAILS_BY_RULE_ID = "/rules/id/{id}/layer-details";
    /**
     * GET /rules/id/{id}/layer-details
     * Returns the LayerDetails for the Rule with the given identifier
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @return Layer-specific access control details. These settings provide fine-grained control over what data and styles can be accessed for a specific layer.  (status code 200)
     *         or The rule has a layer set but does not have LayerDetails set (status code 204)
     *         or Bad request if the rule does not have a layer name set (status code 400)
     *         or Not found if the rule does not exist (status code 404)
     */
    @Operation(
            operationId = "getLayerDetailsByRuleId",
            description = "Returns the LayerDetails for the Rule with the given identifier",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "Layer-specific access control details. These settings provide fine-grained control over what data and styles can be accessed for a specific layer. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = LayerDetails.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = LayerDetails.class))
                        }),
                @ApiResponse(
                        responseCode = "204",
                        description = "The rule has a layer set but does not have LayerDetails set"),
                @ApiResponse(
                        responseCode = "400",
                        description = "Bad request if the rule does not have a layer name set"),
                @ApiResponse(responseCode = "404", description = "Not found if the rule does not exist")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = DataRulesApi.PATH_GET_LAYER_DETAILS_BY_RULE_ID,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<LayerDetails> getLayerDetailsByRuleId(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id) {
        return getDelegate().getLayerDetailsByRuleId(id);
    }

    String PATH_GET_RULE_BY_ID = "/rules/id/{id}";
    /**
     * GET /rules/id/{id} : Get rule by ID
     * Retrieves a specific data rule by its unique identifier.
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @return A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID.  (status code 200)
     *         or No rule exists with the specified ID (status code 404)
     */
    @Operation(
            operationId = "getRuleById",
            summary = "Get rule by ID",
            description = "Retrieves a specific data rule by its unique identifier.",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Rule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = Rule.class))
                        }),
                @ApiResponse(responseCode = "404", description = "No rule exists with the specified ID")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = DataRulesApi.PATH_GET_RULE_BY_ID,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Rule> getRuleById(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id) {
        return getDelegate().getRuleById(id);
    }

    String PATH_GET_RULES = "/rules";
    /**
     * GET /rules : List all data rules
     * Retrieves all data access rules in priority order (lowest priority number first). Supports cursor-based pagination for large rule sets. Use the limit parameter to control page size and the nextCursor parameter to fetch subsequent pages.
     *
     * @param limit Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets.  (optional)
     * @param nextCursor Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets.  (optional)
     * @return A paginated list of data access rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you&#39;ve reached the end of results.  (status code 200)
     */
    @Operation(
            operationId = "getRules",
            summary = "List all data rules",
            description =
                    "Retrieves all data access rules in priority order (lowest priority number first). Supports cursor-based pagination for large rule sets. Use the limit parameter to control page size and the nextCursor parameter to fetch subsequent pages. ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A paginated list of data access rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you've reached the end of results. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    array = @ArraySchema(schema = @Schema(implementation = Rule.class))),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    array = @ArraySchema(schema = @Schema(implementation = Rule.class)))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = DataRulesApi.PATH_GET_RULES,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<List<Rule>> getRules(
            @Parameter(
                            name = "limit",
                            description =
                                    "Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "limit", required = false)
                    @Nullable
                    Integer limit,
            @Parameter(
                            name = "nextCursor",
                            description =
                                    "Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "nextCursor", required = false)
                    @Nullable
                    String nextCursor) {
        return getDelegate().getRules(limit, nextCursor);
    }

    String PATH_QUERY_RULES = "/rules/query";
    /**
     * POST /rules/query : Query data rules with filters
     * Searches for data rules matching the provided filter criteria. Supports cursor-based pagination. The filter allows matching on user, roles, service, request, workspace, layer, and source IP address. Empty filters or wildcard values match any value for that property.
     *
     * @param limit Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets.  (optional)
     * @param nextCursor Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets.  (optional)
     * @param ruleFilter  (optional)
     * @return A paginated list of data access rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you&#39;ve reached the end of results.  (status code 200)
     */
    @Operation(
            operationId = "queryRules",
            summary = "Query data rules with filters",
            description =
                    "Searches for data rules matching the provided filter criteria. Supports cursor-based pagination. The filter allows matching on user, roles, service, request, workspace, layer, and source IP address. Empty filters or wildcard values match any value for that property. ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A paginated list of data access rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you've reached the end of results. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    array = @ArraySchema(schema = @Schema(implementation = Rule.class))),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    array = @ArraySchema(schema = @Schema(implementation = Rule.class)))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = DataRulesApi.PATH_QUERY_RULES,
            produces = {"application/json", "application/x-jackson-smile"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<List<Rule>> queryRules(
            @Parameter(
                            name = "limit",
                            description =
                                    "Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "limit", required = false)
                    @Nullable
                    Integer limit,
            @Parameter(
                            name = "nextCursor",
                            description =
                                    "Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "nextCursor", required = false)
                    @Nullable
                    String nextCursor,
            @Parameter(name = "RuleFilter", description = "") @Valid @RequestBody(required = false) @Nullable
                    RuleFilter ruleFilter) {
        return getDelegate().queryRules(limit, nextCursor, ruleFilter);
    }

    String PATH_RULE_EXISTS_BY_ID = "/rules/id/{id}/exists";
    /**
     * GET /rules/id/{id}/exists : Check if rule exists
     * Checks whether a data rule with the specified ID exists in the system.
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @return Returns true if the rule exists, false otherwise (status code 200)
     */
    @Operation(
            operationId = "ruleExistsById",
            summary = "Check if rule exists",
            description = "Checks whether a data rule with the specified ID exists in the system.",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description = "Returns true if the rule exists, false otherwise",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = Boolean.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = DataRulesApi.PATH_RULE_EXISTS_BY_ID,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Boolean> ruleExistsById(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id) {
        return getDelegate().ruleExistsById(id);
    }

    String PATH_SET_RULE_ALLOWED_STYLES = "/rules/id/{id}/styles";
    /**
     * PUT /rules/id/{id}/styles
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @param requestBody  (optional)
     * @return Updated (status code 204)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "setRuleAllowedStyles",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(responseCode = "204", description = "Updated"),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.PUT,
            value = DataRulesApi.PATH_SET_RULE_ALLOWED_STYLES,
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Void> setRuleAllowedStyles(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id,
            @Parameter(name = "request_body", description = "") @Valid @RequestBody(required = false) @Nullable
                    Set<String> requestBody) {
        return getDelegate().setRuleAllowedStyles(id, requestBody);
    }

    String PATH_SET_RULE_LAYER_DETAILS = "/rules/id/{id}/layer-details";
    /**
     * PUT /rules/id/{id}/layer-details
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @param layerDetails  (optional)
     * @return Updated (status code 204)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "setRuleLayerDetails",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(responseCode = "204", description = "Updated"),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.PUT,
            value = DataRulesApi.PATH_SET_RULE_LAYER_DETAILS,
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Void> setRuleLayerDetails(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id,
            @Parameter(name = "LayerDetails", description = "") @Valid @RequestBody(required = false) @Nullable
                    LayerDetails layerDetails) {
        return getDelegate().setRuleLayerDetails(id, layerDetails);
    }

    String PATH_SET_RULE_LIMITS = "/rules/id/{id}/limits";
    /**
     * PUT /rules/id/{id}/limits
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @param ruleLimits  (optional)
     * @return Updated (status code 204)
     *         or Bad request, the rule is not of LIMIT type (status code 400)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "setRuleLimits",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(responseCode = "204", description = "Updated"),
                @ApiResponse(responseCode = "400", description = "Bad request, the rule is not of LIMIT type"),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.PUT,
            value = DataRulesApi.PATH_SET_RULE_LIMITS,
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Void> setRuleLimits(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id,
            @Parameter(name = "RuleLimits", description = "") @Valid @RequestBody(required = false) @Nullable
                    RuleLimits ruleLimits) {
        return getDelegate().setRuleLimits(id, ruleLimits);
    }

    String PATH_SHIFT_RULES_BY_PRIORITY = "/rules/shift";
    /**
     * POST /rules/shift
     *
     * @param priorityStart The minimum priority to start shifting at (inclusive) (required)
     * @param offset The priority offset to apply to all rules from priorityStart onwards (required)
     * @return The number of rules whose priority was shifted by the required offset (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "shiftRulesByPriority",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description = "The number of rules whose priority was shifted by the required offset",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = Integer.class))
                        }),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = DataRulesApi.PATH_SHIFT_RULES_BY_PRIORITY,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Integer> shiftRulesByPriority(
            @NotNull
                    @Parameter(
                            name = "priorityStart",
                            description = "The minimum priority to start shifting at (inclusive)",
                            required = true,
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "priorityStart", required = true)
                    Long priorityStart,
            @NotNull
                    @Min(value = 1L)
                    @Parameter(
                            name = "offset",
                            description = "The priority offset to apply to all rules from priorityStart onwards",
                            required = true,
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "offset", required = true)
                    Long offset) {
        return getDelegate().shiftRulesByPriority(priorityStart, offset);
    }

    String PATH_SWAP_RULES = "/rules/id/{id}/swapwith/{id2}";
    /**
     * POST /rules/id/{id}/swapwith/{id2}
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @param id2 The rule identifier to swap priorities with (required)
     * @return Updated (status code 204)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "swapRules",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(responseCode = "204", description = "Updated"),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(method = RequestMethod.POST, value = DataRulesApi.PATH_SWAP_RULES)
    default ResponseEntity<Void> swapRules(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id,
            @NotNull
                    @Parameter(
                            name = "id2",
                            description = "The rule identifier to swap priorities with",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id2")
                    String id2) {
        return getDelegate().swapRules(id, id2);
    }

    String PATH_UPDATE_RULE_BY_ID = "/rules/id/{id}";
    /**
     * PATCH /rules/id/{id} : Update an existing data rule
     * Updates an existing data rule. You can modify any property of the rule, including its priority. If you change the rule&#39;s identifier properties (user, role, service, etc.) to match another existing rule, the operation will fail with a 409 Conflict.
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @param rule  (required)
     * @return A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID.  (status code 200)
     *         or Invalid request body or field values (status code 400)
     *         or No rule exists with the specified ID (status code 404)
     *         or The updated rule identifier properties would conflict with another existing rule. Rules must have unique combinations of user, role, service, request, workspace, layer, etc.  (status code 409)
     */
    @Operation(
            operationId = "updateRuleById",
            summary = "Update an existing data rule",
            description =
                    "Updates an existing data rule. You can modify any property of the rule, including its priority. If you change the rule's identifier properties (user, role, service, etc.) to match another existing rule, the operation will fail with a 409 Conflict. ",
            tags = {"DataRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A data access rule. Returned after successfully creating, retrieving, or updating a rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Rule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = Rule.class))
                        }),
                @ApiResponse(responseCode = "400", description = "Invalid request body or field values"),
                @ApiResponse(responseCode = "404", description = "No rule exists with the specified ID"),
                @ApiResponse(
                        responseCode = "409",
                        description =
                                "The updated rule identifier properties would conflict with another existing rule. Rules must have unique combinations of user, role, service, request, workspace, layer, etc. ")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.PATCH,
            value = DataRulesApi.PATH_UPDATE_RULE_BY_ID,
            produces = {"application/json", "application/x-jackson-smile"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Rule> updateRuleById(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id,
            @Parameter(name = "Rule", description = "", required = true) @Valid @RequestBody Rule rule) {
        return getDelegate().updateRuleById(id, rule);
    }
}
