/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.17.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.geoserver.acl.webapi.v1.server;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import org.geoserver.acl.webapi.v1.model.AdminRule;
import org.geoserver.acl.webapi.v1.model.AdminRuleFilter;
import org.geoserver.acl.webapi.v1.model.InsertPosition;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.Nullable;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2026-01-29T18:51:14.805992-03:00[America/Argentina/Cordoba]",
        comments = "Generator version: 7.17.0")
@Validated
@Tag(
        name = "WorkspaceAdminRules",
        description =
                "Manage workspace administration rules that grant or restrict administrative privileges on GeoServer workspaces. These rules determine whether users can modify workspace configuration and content. ")
public interface WorkspaceAdminRulesApi {

    default WorkspaceAdminRulesApiDelegate getDelegate() {
        return new WorkspaceAdminRulesApiDelegate() {};
    }

    String PATH_ADMIN_RULE_EXISTS_BY_ID = "/adminrules/id/{id}/exists";
    /**
     * GET /adminrules/id/{id}/exists
     * Returns whether the AdminRule with the given identifier exists
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @return boolean indicating whether the admin rule with the provided identifier exists (status code 200)
     */
    @Operation(
            operationId = "adminRuleExistsById",
            description = "Returns whether the AdminRule with the given identifier exists",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description = "boolean indicating whether the admin rule with the provided identifier exists",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Boolean.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = Boolean.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = WorkspaceAdminRulesApi.PATH_ADMIN_RULE_EXISTS_BY_ID,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Boolean> adminRuleExistsById(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id) {
        return getDelegate().adminRuleExistsById(id);
    }

    String PATH_COUNT_ADMIN_RULES = "/adminrules/query/count";
    /**
     * POST /adminrules/query/count
     * Returns the number of rules that matches the search criteria
     *
     * @param adminRuleFilter  (required)
     * @return The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used.  (status code 200)
     */
    @Operation(
            operationId = "countAdminRules",
            description = "Returns the number of rules that matches the search criteria",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = WorkspaceAdminRulesApi.PATH_COUNT_ADMIN_RULES,
            produces = {"application/json"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<Integer> countAdminRules(
            @Parameter(name = "AdminRuleFilter", description = "", required = true) @Valid @RequestBody
                    AdminRuleFilter adminRuleFilter) {
        return getDelegate().countAdminRules(adminRuleFilter);
    }

    String PATH_COUNT_ALL_ADMIN_RULES = "/adminrules/query/count";
    /**
     * GET /adminrules/query/count
     * Returns the total number of rules
     *
     * @return The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used.  (status code 200)
     */
    @Operation(
            operationId = "countAllAdminRules",
            description = "Returns the total number of rules",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = WorkspaceAdminRulesApi.PATH_COUNT_ALL_ADMIN_RULES,
            produces = {"application/json"})
    default ResponseEntity<Integer> countAllAdminRules() {

        return getDelegate().countAllAdminRules();
    }

    String PATH_CREATE_ADMIN_RULE = "/adminrules";
    /**
     * POST /adminrules
     *
     * @param adminRule  (required)
     * @param position Controls how the rule&#39;s priority value should be interpreted when inserting a new rule. See the InsertPosition schema for detailed explanation of FIXED, FROM_START, and FROM_END options. Defaults to FIXED if not specified.  (optional)
     * @return A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID.  (status code 201)
     */
    @Operation(
            operationId = "createAdminRule",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "201",
                        description =
                                "A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = AdminRule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = AdminRule.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = WorkspaceAdminRulesApi.PATH_CREATE_ADMIN_RULE,
            produces = {"application/json", "application/x-jackson-smile"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<AdminRule> createAdminRule(
            @Parameter(name = "AdminRule", description = "", required = true) @Valid @RequestBody AdminRule adminRule,
            @Parameter(
                            name = "position",
                            description =
                                    "Controls how the rule's priority value should be interpreted when inserting a new rule. See the InsertPosition schema for detailed explanation of FIXED, FROM_START, and FROM_END options. Defaults to FIXED if not specified. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "position", required = false)
                    @Nullable
                    InsertPosition position) {
        return getDelegate().createAdminRule(adminRule, position);
    }

    String PATH_DELETE_ADMIN_RULE_BY_ID = "/adminrules/id/{id}";
    /**
     * DELETE /adminrules/id/{id}
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @return OK (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "deleteAdminRuleById",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(responseCode = "200", description = "OK"),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(method = RequestMethod.DELETE, value = WorkspaceAdminRulesApi.PATH_DELETE_ADMIN_RULE_BY_ID)
    default ResponseEntity<Void> deleteAdminRuleById(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id) {
        return getDelegate().deleteAdminRuleById(id);
    }

    String PATH_DELETE_ALL_ADMIN_RULES = "/adminrules";
    /**
     * DELETE /adminrules
     * Atomically deletes all admin rules and return the number of rules removed
     *
     * @return The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used.  (status code 200)
     */
    @Operation(
            operationId = "deleteAllAdminRules",
            description = "Atomically deletes all admin rules and return the number of rules removed",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "The total number of rules that match the query criteria. This count represents the full result set, not just the current page if pagination is being used. ",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.DELETE,
            value = WorkspaceAdminRulesApi.PATH_DELETE_ALL_ADMIN_RULES,
            produces = {"application/json"})
    default ResponseEntity<Integer> deleteAllAdminRules() {

        return getDelegate().deleteAllAdminRules();
    }

    String PATH_FIND_ADMIN_RULES = "/adminrules/query";
    /**
     * POST /adminrules/query
     *
     * @param limit Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets.  (optional)
     * @param nextCursor Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets.  (optional)
     * @param adminRuleFilter  (optional)
     * @return A paginated list of workspace admin rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you&#39;ve reached the end of results.  (status code 200)
     */
    @Operation(
            operationId = "findAdminRules",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A paginated list of workspace admin rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you've reached the end of results. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    array = @ArraySchema(schema = @Schema(implementation = AdminRule.class))),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    array = @ArraySchema(schema = @Schema(implementation = AdminRule.class)))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = WorkspaceAdminRulesApi.PATH_FIND_ADMIN_RULES,
            produces = {"application/json", "application/x-jackson-smile"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<List<AdminRule>> findAdminRules(
            @Parameter(
                            name = "limit",
                            description =
                                    "Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "limit", required = false)
                    @Nullable
                    Integer limit,
            @Parameter(
                            name = "nextCursor",
                            description =
                                    "Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "nextCursor", required = false)
                    @Nullable
                    String nextCursor,
            @Parameter(name = "AdminRuleFilter", description = "") @Valid @RequestBody(required = false) @Nullable
                    AdminRuleFilter adminRuleFilter) {
        return getDelegate().findAdminRules(limit, nextCursor, adminRuleFilter);
    }

    String PATH_FIND_ALL_ADMIN_RULES = "/adminrules";
    /**
     * GET /adminrules
     * Returns an (optionally) paginated list of admin rules.
     *
     * @param limit Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets.  (optional)
     * @param nextCursor Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets.  (optional)
     * @return A paginated list of workspace admin rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you&#39;ve reached the end of results.  (status code 200)
     */
    @Operation(
            operationId = "findAllAdminRules",
            description = "Returns an (optionally) paginated list of admin rules.",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A paginated list of workspace admin rules matching the query criteria. Rules are returned in priority order (lowest priority number first). If more rules exist beyond this page, check the X-ACL-NEXTCURSOR header to fetch the next page. An empty array indicates no rules match or you've reached the end of results. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    array = @ArraySchema(schema = @Schema(implementation = AdminRule.class))),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    array = @ArraySchema(schema = @Schema(implementation = AdminRule.class)))
                        })
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = WorkspaceAdminRulesApi.PATH_FIND_ALL_ADMIN_RULES,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<List<AdminRule>> findAllAdminRules(
            @Parameter(
                            name = "limit",
                            description =
                                    "Maximum number of items to return in a single page. If more items match the query than this limit, the response will include an X-ACL-NEXTCURSOR header with a cursor value to fetch the next page. Use in combination with nextCursor to paginate through large result sets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "limit", required = false)
                    @Nullable
                    Integer limit,
            @Parameter(
                            name = "nextCursor",
                            description =
                                    "Cursor for pagination. When a response includes an X-ACL-NEXTCURSOR header, use that value here to fetch the next page of results. Continue until X-ACL-NEXTCURSOR is null or absent, indicating no more results are available. This implements efficient cursor-based pagination that works well with large datasets. ",
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "nextCursor", required = false)
                    @Nullable
                    String nextCursor) {
        return getDelegate().findAllAdminRules(limit, nextCursor);
    }

    String PATH_FIND_FIRST_ADMIN_RULE = "/adminrules/query/first";
    /**
     * POST /adminrules/query/first
     * Finds the first rule that satisfies the query criteria
     *
     * @param adminRuleFilter  (required)
     * @return A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID.  (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "findFirstAdminRule",
            description = "Finds the first rule that satisfies the query criteria",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = AdminRule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = AdminRule.class))
                        }),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = WorkspaceAdminRulesApi.PATH_FIND_FIRST_ADMIN_RULE,
            produces = {"application/json", "application/x-jackson-smile"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<AdminRule> findFirstAdminRule(
            @Parameter(name = "AdminRuleFilter", description = "", required = true) @Valid @RequestBody
                    AdminRuleFilter adminRuleFilter) {
        return getDelegate().findFirstAdminRule(adminRuleFilter);
    }

    String PATH_FIND_ONE_ADMIN_RULE_BY_PRIORITY = "/adminrules/query/one/priority/{priority}";
    /**
     * GET /adminrules/query/one/priority/{priority}
     * Finds the AdminRule with the given priority
     *
     * @param priority The rule priority to search for (required)
     * @return A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID.  (status code 200)
     *         or Not found (status code 404)
     *         or Conflict, there&#39;s more than one rule with the requested priority (status code 409)
     */
    @Operation(
            operationId = "findOneAdminRuleByPriority",
            description = "Finds the AdminRule with the given priority",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = AdminRule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = AdminRule.class))
                        }),
                @ApiResponse(responseCode = "404", description = "Not found"),
                @ApiResponse(
                        responseCode = "409",
                        description = "Conflict, there's more than one rule with the requested priority")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = WorkspaceAdminRulesApi.PATH_FIND_ONE_ADMIN_RULE_BY_PRIORITY,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<AdminRule> findOneAdminRuleByPriority(
            @NotNull
                    @Parameter(
                            name = "priority",
                            description = "The rule priority to search for",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("priority")
                    Long priority) {
        return getDelegate().findOneAdminRuleByPriority(priority);
    }

    String PATH_GET_ADMIN_RULE_BY_ID = "/adminrules/id/{id}";
    /**
     * GET /adminrules/id/{id}
     * Returns the AdminRule with the given identifier
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @return A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID.  (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "getAdminRuleById",
            description = "Returns the AdminRule with the given identifier",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = AdminRule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = AdminRule.class))
                        }),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.GET,
            value = WorkspaceAdminRulesApi.PATH_GET_ADMIN_RULE_BY_ID,
            produces = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<AdminRule> getAdminRuleById(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id) {
        return getDelegate().getAdminRuleById(id);
    }

    String PATH_SHIFT_ADMIN_RULES_BY_PRIORITY = "/adminrules/shift";
    /**
     * POST /adminrules/shift
     *
     * @param priorityStart The minimum priority to start shifting at (inclusive) (required)
     * @param offset The priority offset to apply to all rules from priorityStart onwards (required)
     * @return The number of admin rules whose priority was shifted by the required offset (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "shiftAdminRulesByPriority",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description = "The number of admin rules whose priority was shifted by the required offset",
                        content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Integer.class))
                        }),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.POST,
            value = WorkspaceAdminRulesApi.PATH_SHIFT_ADMIN_RULES_BY_PRIORITY,
            produces = {"application/json"})
    default ResponseEntity<Integer> shiftAdminRulesByPriority(
            @NotNull
                    @Parameter(
                            name = "priorityStart",
                            description = "The minimum priority to start shifting at (inclusive)",
                            required = true,
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "priorityStart", required = true)
                    Long priorityStart,
            @NotNull
                    @Min(value = 1L)
                    @Parameter(
                            name = "offset",
                            description = "The priority offset to apply to all rules from priorityStart onwards",
                            required = true,
                            in = ParameterIn.QUERY)
                    @Valid
                    @RequestParam(value = "offset", required = true)
                    Long offset) {
        return getDelegate().shiftAdminRulesByPriority(priorityStart, offset);
    }

    String PATH_SWAP_ADMIN_RULES = "/adminrules/id/{id}/swapwith/{id2}";
    /**
     * POST /adminrules/id/{id}/swapwith/{id2}
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @param id2 The admin rule identifier to swap priorities with (required)
     * @return Updated (status code 204)
     *         or Not found (status code 404)
     */
    @Operation(
            operationId = "swapAdminRules",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(responseCode = "204", description = "Updated"),
                @ApiResponse(responseCode = "404", description = "Not found")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(method = RequestMethod.POST, value = WorkspaceAdminRulesApi.PATH_SWAP_ADMIN_RULES)
    default ResponseEntity<Void> swapAdminRules(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id,
            @NotNull
                    @Parameter(
                            name = "id2",
                            description = "The admin rule identifier to swap priorities with",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id2")
                    String id2) {
        return getDelegate().swapAdminRules(id, id2);
    }

    String PATH_UPDATE_ADMIN_RULE = "/adminrules/id/{id}";
    /**
     * PATCH /adminrules/id/{id}
     *
     * @param id Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance.  (required)
     * @param adminRule  (required)
     * @return A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID.  (status code 200)
     *         or Bad request body (status code 400)
     *         or Not found (status code 404)
     *         or Conflict, tried to update the rule identifier properties to one that belongs to another rule (status code 409)
     */
    @Operation(
            operationId = "updateAdminRule",
            tags = {"WorkspaceAdminRules"},
            responses = {
                @ApiResponse(
                        responseCode = "200",
                        description =
                                "A workspace administration rule. Returned after successfully creating, retrieving, or updating an admin rule. The response includes the complete rule definition with its system-generated ID. ",
                        content = {
                            @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(implementation = AdminRule.class)),
                            @Content(
                                    mediaType = "application/x-jackson-smile",
                                    schema = @Schema(implementation = AdminRule.class))
                        }),
                @ApiResponse(responseCode = "400", description = "Bad request body"),
                @ApiResponse(responseCode = "404", description = "Not found"),
                @ApiResponse(
                        responseCode = "409",
                        description =
                                "Conflict, tried to update the rule identifier properties to one that belongs to another rule")
            },
            security = {@SecurityRequirement(name = "basicAuth")})
    @RequestMapping(
            method = RequestMethod.PATCH,
            value = WorkspaceAdminRulesApi.PATH_UPDATE_ADMIN_RULE,
            produces = {"application/json", "application/x-jackson-smile"},
            consumes = {"application/json", "application/x-jackson-smile"})
    default ResponseEntity<AdminRule> updateAdminRule(
            @NotNull
                    @Parameter(
                            name = "id",
                            description =
                                    "Unique identifier for the rule. This is a system-generated ID that uniquely identifies a specific rule instance. ",
                            required = true,
                            in = ParameterIn.PATH)
                    @PathVariable("id")
                    String id,
            @Parameter(name = "AdminRule", description = "", required = true) @Valid @RequestBody AdminRule adminRule) {
        return getDelegate().updateAdminRule(id, adminRule);
    }
}
