package org.geoserver.acl.webapi.v1.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.Objects;
import org.springframework.lang.Nullable;

/**
 * A workspace administration rule that determines whether users have administrative privileges on specific workspaces. Admin rules are simpler than data rules - they only match on user, role, workspace, and IP address, and grant either ADMIN or USER level access.  Rules are evaluated in priority order (lower numbers first) until a match is found. Like data rules, admin rules are uniquely identified by the combination of their matching criteria.
 */
@Schema(
        name = "AdminRule",
        description =
                "A workspace administration rule that determines whether users have administrative privileges on specific workspaces. Admin rules are simpler than data rules - they only match on user, role, workspace, and IP address, and grant either ADMIN or USER level access.  Rules are evaluated in priority order (lower numbers first) until a match is found. Like data rules, admin rules are uniquely identified by the combination of their matching criteria. ")
@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2026-01-29T18:56:08.226482-03:00[America/Argentina/Cordoba]",
        comments = "Generator version: 7.19.0")
public class AdminRule {

    private @Nullable String id = null;

    private Long priority;

    private AdminGrantType access = null;

    private @Nullable String extId = null;

    private @Nullable String name = null;

    private @Nullable String description = null;

    private @Nullable String role = null;

    private @Nullable String user = null;

    private @Nullable String workspace = null;

    private @Nullable String addressRange = null;

    public AdminRule() {
        super();
    }

    /**
     * Constructor with only required parameters
     */
    public AdminRule(Long priority, AdminGrantType access) {
        this.priority = priority;
        this.access = access;
    }

    public AdminRule id(@Nullable String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique identifier for the rule. Auto-generated by the system.
     * @return id
     */
    @Schema(
            name = "id",
            description = "Unique identifier for the rule. Auto-generated by the system.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("id")
    public @Nullable String getId() {
        return id;
    }

    public void setId(@Nullable String id) {
        this.id = id;
    }

    public AdminRule priority(Long priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Evaluation order for this rule. Lower numbers have higher priority and are evaluated first.
     * @return priority
     */
    @NotNull
    @Schema(
            name = "priority",
            example = "50",
            description =
                    "Evaluation order for this rule. Lower numbers have higher priority and are evaluated first. ",
            requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty("priority")
    public Long getPriority() {
        return priority;
    }

    public void setPriority(Long priority) {
        this.priority = priority;
    }

    public AdminRule access(AdminGrantType access) {
        this.access = access;
        return this;
    }

    /**
     * Get access
     * @return access
     */
    @NotNull
    @Valid
    @Schema(name = "access", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty("access")
    public AdminGrantType getAccess() {
        return access;
    }

    public void setAccess(AdminGrantType access) {
        this.access = access;
    }

    public AdminRule extId(@Nullable String extId) {
        this.extId = extId;
        return this;
    }

    /**
     * External identifier for integration with other systems.
     * @return extId
     */
    @Schema(
            name = "extId",
            description = "External identifier for integration with other systems.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("extId")
    public @Nullable String getExtId() {
        return extId;
    }

    public void setExtId(@Nullable String extId) {
        this.extId = extId;
    }

    public AdminRule name(@Nullable String name) {
        this.name = name;
        return this;
    }

    /**
     * Human-readable name for this admin rule.
     * @return name
     */
    @Schema(
            name = "name",
            example = "Grant admin access to cartography workspace",
            description = "Human-readable name for this admin rule.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("name")
    public @Nullable String getName() {
        return name;
    }

    public void setName(@Nullable String name) {
        this.name = name;
    }

    public AdminRule description(@Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Detailed description explaining the purpose of this admin rule.
     * @return description
     */
    @Schema(
            name = "description",
            description = "Detailed description explaining the purpose of this admin rule.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("description")
    public @Nullable String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    public AdminRule role(@Nullable String role) {
        this.role = role;
        return this;
    }

    /**
     * Get role
     * @return role
     */
    @Schema(name = "role", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("role")
    public @Nullable String getRole() {
        return role;
    }

    public void setRole(@Nullable String role) {
        this.role = role;
    }

    public AdminRule user(@Nullable String user) {
        this.user = user;
        return this;
    }

    /**
     * Get user
     * @return user
     */
    @Schema(name = "user", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("user")
    public @Nullable String getUser() {
        return user;
    }

    public void setUser(@Nullable String user) {
        this.user = user;
    }

    public AdminRule workspace(@Nullable String workspace) {
        this.workspace = workspace;
        return this;
    }

    /**
     * Get workspace
     * @return workspace
     */
    @Schema(name = "workspace", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("workspace")
    public @Nullable String getWorkspace() {
        return workspace;
    }

    public void setWorkspace(@Nullable String workspace) {
        this.workspace = workspace;
    }

    public AdminRule addressRange(@Nullable String addressRange) {
        this.addressRange = addressRange;
        return this;
    }

    /**
     * IPv4 address range in CIDR notation. Can be a single IP address (e.g., \"192.168.1.1\") or a range using subnet mask notation (e.g., \"192.168.1.0/24\").
     * @return addressRange
     */
    @Pattern(regexp = "^([0-9]{1,3}\\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$")
    @Schema(
            name = "addressRange",
            example = "192.168.1.0/24",
            description =
                    "IPv4 address range in CIDR notation. Can be a single IP address (e.g., \"192.168.1.1\") or a range using subnet mask notation (e.g., \"192.168.1.0/24\"). ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("addressRange")
    public @Nullable String getAddressRange() {
        return addressRange;
    }

    public void setAddressRange(@Nullable String addressRange) {
        this.addressRange = addressRange;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdminRule adminRule = (AdminRule) o;
        return Objects.equals(this.id, adminRule.id)
                && Objects.equals(this.priority, adminRule.priority)
                && Objects.equals(this.access, adminRule.access)
                && Objects.equals(this.extId, adminRule.extId)
                && Objects.equals(this.name, adminRule.name)
                && Objects.equals(this.description, adminRule.description)
                && Objects.equals(this.role, adminRule.role)
                && Objects.equals(this.user, adminRule.user)
                && Objects.equals(this.workspace, adminRule.workspace)
                && Objects.equals(this.addressRange, adminRule.addressRange);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, priority, access, extId, name, description, role, user, workspace, addressRange);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AdminRule {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
        sb.append("    access: ").append(toIndentedString(access)).append("\n");
        sb.append("    extId: ").append(toIndentedString(extId)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
        sb.append("    addressRange: ").append(toIndentedString(addressRange)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(@Nullable Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
