package org.geoserver.acl.webapi.v1.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.Objects;
import org.springframework.lang.Nullable;

/**
 * A data access rule that controls permissions for GeoServer resources. Rules are evaluated in priority order (lower numbers first) to determine whether a request should be allowed, denied, or limited.  Each rule matches requests based on a combination of criteria: user, role, IP address, OWS service type, request type, workspace, and layer. Properties set to null act as wildcards that match any value.  Rules are uniquely identified by the combination of: user, role, service, request, subfield, workspace, layer, and addressRange. This means you cannot have two rules with the exact same matching criteria.
 */
@Schema(
        name = "Rule",
        description =
                "A data access rule that controls permissions for GeoServer resources. Rules are evaluated in priority order (lower numbers first) to determine whether a request should be allowed, denied, or limited.  Each rule matches requests based on a combination of criteria: user, role, IP address, OWS service type, request type, workspace, and layer. Properties set to null act as wildcards that match any value.  Rules are uniquely identified by the combination of: user, role, service, request, subfield, workspace, layer, and addressRange. This means you cannot have two rules with the exact same matching criteria. ")
@Generated(
        value = "org.openapitools.codegen.languages.SpringCodegen",
        date = "2026-01-29T18:56:08.226482-03:00[America/Argentina/Cordoba]",
        comments = "Generator version: 7.19.0")
public class Rule {

    private @Nullable String id = null;

    private Long priority;

    private @Nullable String extId = null;

    private @Nullable String name = null;

    private @Nullable String description = null;

    private GrantType access = null;

    private @Nullable RuleLimits limits = null;

    private @Nullable String role = null;

    private @Nullable String user = null;

    private @Nullable String addressRange = null;

    private @Nullable String service = null;

    private @Nullable String request = null;

    private @Nullable String subfield = null;

    private @Nullable String workspace = null;

    private @Nullable String layer = null;

    public Rule() {
        super();
    }

    /**
     * Constructor with only required parameters
     */
    public Rule(Long priority, GrantType access) {
        this.priority = priority;
        this.access = access;
    }

    public Rule id(@Nullable String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique identifier for the rule. Auto-generated by the system.
     * @return id
     */
    @Schema(
            name = "id",
            description = "Unique identifier for the rule. Auto-generated by the system.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("id")
    public @Nullable String getId() {
        return id;
    }

    public void setId(@Nullable String id) {
        this.id = id;
    }

    public Rule priority(Long priority) {
        this.priority = priority;
        return this;
    }

    /**
     * Evaluation order for this rule. Lower numbers have higher priority and are evaluated first. The first matching rule determines the access decision.
     * @return priority
     */
    @NotNull
    @Schema(
            name = "priority",
            example = "100",
            description =
                    "Evaluation order for this rule. Lower numbers have higher priority and are evaluated first. The first matching rule determines the access decision. ",
            requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty("priority")
    public Long getPriority() {
        return priority;
    }

    public void setPriority(Long priority) {
        this.priority = priority;
    }

    public Rule extId(@Nullable String extId) {
        this.extId = extId;
        return this;
    }

    /**
     * External identifier for integration with other systems.
     * @return extId
     */
    @Schema(
            name = "extId",
            description = "External identifier for integration with other systems.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("extId")
    public @Nullable String getExtId() {
        return extId;
    }

    public void setExtId(@Nullable String extId) {
        this.extId = extId;
    }

    public Rule name(@Nullable String name) {
        this.name = name;
        return this;
    }

    /**
     * Human-readable name for this rule.
     * @return name
     */
    @Schema(
            name = "name",
            example = "Allow WMS access to roads layer",
            description = "Human-readable name for this rule.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("name")
    public @Nullable String getName() {
        return name;
    }

    public void setName(@Nullable String name) {
        this.name = name;
    }

    public Rule description(@Nullable String description) {
        this.description = description;
        return this;
    }

    /**
     * Detailed description explaining the purpose of this rule.
     * @return description
     */
    @Schema(
            name = "description",
            description = "Detailed description explaining the purpose of this rule.",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("description")
    public @Nullable String getDescription() {
        return description;
    }

    public void setDescription(@Nullable String description) {
        this.description = description;
    }

    public Rule access(GrantType access) {
        this.access = access;
        return this;
    }

    /**
     * Get access
     * @return access
     */
    @NotNull
    @Valid
    @Schema(name = "access", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty("access")
    public GrantType getAccess() {
        return access;
    }

    public void setAccess(GrantType access) {
        this.access = access;
    }

    public Rule limits(@Nullable RuleLimits limits) {
        this.limits = limits;
        return this;
    }

    /**
     * Get limits
     * @return limits
     */
    @Valid
    @Schema(name = "limits", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("limits")
    public @Nullable RuleLimits getLimits() {
        return limits;
    }

    public void setLimits(@Nullable RuleLimits limits) {
        this.limits = limits;
    }

    public Rule role(@Nullable String role) {
        this.role = role;
        return this;
    }

    /**
     * Role name to match. Null matches any role. The request matches if the user has this role.
     * @return role
     */
    @Schema(
            name = "role",
            example = "ROLE_VIEWER",
            description = "Role name to match. Null matches any role. The request matches if the user has this role. ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("role")
    public @Nullable String getRole() {
        return role;
    }

    public void setRole(@Nullable String role) {
        this.role = role;
    }

    public Rule user(@Nullable String user) {
        this.user = user;
        return this;
    }

    /**
     * Username to match. Null matches any user. Use \"*\" to explicitly match anonymous users.
     * @return user
     */
    @Schema(
            name = "user",
            example = "john.doe",
            description = "Username to match. Null matches any user. Use \"*\" to explicitly match anonymous users. ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("user")
    public @Nullable String getUser() {
        return user;
    }

    public void setUser(@Nullable String user) {
        this.user = user;
    }

    public Rule addressRange(@Nullable String addressRange) {
        this.addressRange = addressRange;
        return this;
    }

    /**
     * IPv4 address range in CIDR notation. Can be a single IP address (e.g., \"192.168.1.1\") or a range using subnet mask notation (e.g., \"192.168.1.0/24\").
     * @return addressRange
     */
    @Pattern(regexp = "^([0-9]{1,3}\\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$")
    @Schema(
            name = "addressRange",
            example = "192.168.1.0/24",
            description =
                    "IPv4 address range in CIDR notation. Can be a single IP address (e.g., \"192.168.1.1\") or a range using subnet mask notation (e.g., \"192.168.1.0/24\"). ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("addressRange")
    public @Nullable String getAddressRange() {
        return addressRange;
    }

    public void setAddressRange(@Nullable String addressRange) {
        this.addressRange = addressRange;
    }

    public Rule service(@Nullable String service) {
        this.service = service;
        return this;
    }

    /**
     * OWS service type to match (e.g., WMS, WFS, WCS, WPS). Null matches any service.
     * @return service
     */
    @Schema(
            name = "service",
            example = "WMS",
            description = "OWS service type to match (e.g., WMS, WFS, WCS, WPS). Null matches any service. ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("service")
    public @Nullable String getService() {
        return service;
    }

    public void setService(@Nullable String service) {
        this.service = service;
    }

    public Rule request(@Nullable String request) {
        this.request = request;
        return this;
    }

    /**
     * OWS request operation to match (e.g., GetMap, GetFeature, GetCoverage). Null matches any request.
     * @return request
     */
    @Schema(
            name = "request",
            example = "GetMap",
            description =
                    "OWS request operation to match (e.g., GetMap, GetFeature, GetCoverage). Null matches any request. ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("request")
    public @Nullable String getRequest() {
        return request;
    }

    public void setRequest(@Nullable String request) {
        this.request = request;
    }

    public Rule subfield(@Nullable String subfield) {
        this.subfield = subfield;
        return this;
    }

    /**
     * Additional request-specific qualifier. Used for fine-grained control within a request type.
     * @return subfield
     */
    @Schema(
            name = "subfield",
            description =
                    "Additional request-specific qualifier. Used for fine-grained control within a request type. ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("subfield")
    public @Nullable String getSubfield() {
        return subfield;
    }

    public void setSubfield(@Nullable String subfield) {
        this.subfield = subfield;
    }

    public Rule workspace(@Nullable String workspace) {
        this.workspace = workspace;
        return this;
    }

    /**
     * Workspace name to match. Null matches any workspace.
     * @return workspace
     */
    @Schema(
            name = "workspace",
            example = "topp",
            description = "Workspace name to match. Null matches any workspace. ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("workspace")
    public @Nullable String getWorkspace() {
        return workspace;
    }

    public void setWorkspace(@Nullable String workspace) {
        this.workspace = workspace;
    }

    public Rule layer(@Nullable String layer) {
        this.layer = layer;
        return this;
    }

    /**
     * Layer name to match. Null matches any layer within the matched workspace.
     * @return layer
     */
    @Schema(
            name = "layer",
            example = "roads",
            description = "Layer name to match. Null matches any layer within the matched workspace. ",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @JsonProperty("layer")
    public @Nullable String getLayer() {
        return layer;
    }

    public void setLayer(@Nullable String layer) {
        this.layer = layer;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Rule rule = (Rule) o;
        return Objects.equals(this.id, rule.id)
                && Objects.equals(this.priority, rule.priority)
                && Objects.equals(this.extId, rule.extId)
                && Objects.equals(this.name, rule.name)
                && Objects.equals(this.description, rule.description)
                && Objects.equals(this.access, rule.access)
                && Objects.equals(this.limits, rule.limits)
                && Objects.equals(this.role, rule.role)
                && Objects.equals(this.user, rule.user)
                && Objects.equals(this.addressRange, rule.addressRange)
                && Objects.equals(this.service, rule.service)
                && Objects.equals(this.request, rule.request)
                && Objects.equals(this.subfield, rule.subfield)
                && Objects.equals(this.workspace, rule.workspace)
                && Objects.equals(this.layer, rule.layer);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                id,
                priority,
                extId,
                name,
                description,
                access,
                limits,
                role,
                user,
                addressRange,
                service,
                request,
                subfield,
                workspace,
                layer);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Rule {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
        sb.append("    extId: ").append(toIndentedString(extId)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    access: ").append(toIndentedString(access)).append("\n");
        sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("    addressRange: ").append(toIndentedString(addressRange)).append("\n");
        sb.append("    service: ").append(toIndentedString(service)).append("\n");
        sb.append("    request: ").append(toIndentedString(request)).append("\n");
        sb.append("    subfield: ").append(toIndentedString(subfield)).append("\n");
        sb.append("    workspace: ").append(toIndentedString(workspace)).append("\n");
        sb.append("    layer: ").append(toIndentedString(layer)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(@Nullable Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
