spring:
  flyway:
    enabled: true
    # this will create the schema if doesn't exist
    # note the same property is used by geoserver.acl.jpa.properties.hibernate.default_schema
    default-schema: ${acl.db.schema:acl} 

geoserver.acl:
  datasource:
    jndi-name: ${acl.db.jndiName:} 
    url: ${acl.db.url:}
    username: ${acl.db.username:}
    password: ${acl.db.password:}
    hikari:
      minimum-idle: ${acl.db.hikari.minimumIdle:1}
      maximum-pool-size: ${acl.db.hikari.maximumPoolSize:20}
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ${acl.db.schema:acl}
        hbm2ddl.auto: ${acl.db.hbm2ddl.auto:validate}
        dialect: ${acl.db.dialect:org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect} 
  security:
    headers:
      enabled: ${acl.security.headers.enabled:false}
      user-header: ${acl.security.headers.user-header:sec-username}
      roles-header: ${acl.security.headers.roles-header:sec-roles}
      admin-roles: ["ROLE_ADMINISTRATOR"]
    internal:
      enabled: ${acl.security.basic.enabled:true}
      users:
        admin:
          admin: true
          enabled: ${acl.users.admin.enabled:false}
          password: ${acl.users.admin.password:}
          # password is the bcrypt encoded value, for example, for pwd s3cr3t:
          # password: "{bcrypt}$2a$10$eMyaZRLZBAZdor8nOX.qwuwOyWazXjR2hddGLCT6f6c382WiwdQGG"
#        user:
#          admin: false
#          enabled: true
#          # password is the bcrypt encoded value for s3cr3t
#          password: "{bcrypt}$2a$10$eMyaZRLZBAZdor8nOX.qwuwOyWazXjR2hddGLCT6f6c382WiwdQGG"

---
spring.config.activate.on-profile: local
server.port: 9000

jndi:
  datasources:
    acl:
      enabled: true
      wait-for-it: true
      wait-timeout: 15
      url: jdbc:postgresql://localhost:6432/acl
      username: acl
      password: acls3cr3t
      maximum-pool-size: 50
      minimum-idle: 2
      connection-timeout: 3000
      idle-timeout: 60000

acl.db.jndiName: java:comp/env/jdbc/acl
acl.users.admin.enabled: true
acl.users.admin.password: "{bcrypt}$2a$10$eMyaZRLZBAZdor8nOX.qwuwOyWazXjR2hddGLCT6f6c382WiwdQGG"
---
spring.config.activate.on-profile: dev

acl.db.dialect: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
acl.db.schema: ''

spring.flyway.enabled: false
geoserver.acl.jpa.properties.hibernate.hbm2ddl.auto: create
geoserver.acl.jpa.properties.show-sql: false

acl.security.headers.enabled: true
acl.users.admin.enabled: true
acl.users.admin.password: "{bcrypt}$2a$10$eMyaZRLZBAZdor8nOX.qwuwOyWazXjR2hddGLCT6f6c382WiwdQGG"

geoserver:
  acl:
    datasource:
      url: jdbc:h2:mem:geoserver-acl;DB_CLOSE_DELAY=-1
      hikari:
        minimum-idle: 1
        maximum-pool-size: 20

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

