
# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem "jekyll", ENV["JEKYLL_VERSION"] if ENV["JEKYLL_VERSION"]
gem "kramdown-parser-gfm" if ENV["JEKYLL_VERSION"] == "~> 3.9"

gem "webrick", "= 1.8.1"

gem "rss", "= 0.2.9"

gem "open-uri", "= 0.1.0"

gem "rails", "= 6.1.7.2"

gem "yaml", "= 0.2.1"

gem "nokogiri", "= 1.14.2"

gem 'jekyll_picture_tag', '= 2.0.4'
