/* (c) 2023  Open Source Geospatial Foundation - all rights reserved
 * This code is licensed under the GPL 2.0 license, available at the root
 * application directory.
 *
 * Original from GeoFence 3.6 under GPL 2.0 license
 */

package org.geoserver.acl.domain.rules;

import lombok.Builder;
import lombok.With;
import org.jspecify.annotations.Nullable;

/**
 * Data access control rule for GeoServer resources.
 *
 * <p>Defines who can access what GeoServer resources (workspaces, layers, services) and what level
 * of access they have (allow, deny, or limit).
 *
 * <p>Rules are evaluated in strict priority order (lower numbers first). The first matching rule
 * determines the access decision. Example:
 * <pre>{@code
 * Priority 1: username="alice", workspace="topp", layer="states" -> ALLOW
 * Priority 2: username="alice", workspace="topp" -> DENY
 * Priority 3: username="alice" -> ALLOW
 * }</pre>
 * When alice requests "topp:states", Rule 1 matches first and grants access. For "topp:roads",
 * Rule 2 matches and denies access.
 *
 * <p>Components:
 * <ul>
 *   <li>{@link RuleIdentifier}: Matching criteria (user, role, IP, service, workspace, layer)
 *   <li>{@link GrantType}: Access type (ALLOW, DENY, LIMIT)
 *   <li>{@link RuleLimits}: Restrictions for LIMIT rules (spatial constraints, catalog mode)
 *   <li>{@link LayerDetails}: Detailed permissions for ALLOW rules (CQL filters, styles, attributes)
 * </ul>
 *
 * <p>Priority is a {@code long} where lower numbers = higher priority. No two rules can have the
 * same priority. {@link RuleAdminService} can automatically shift priorities to maintain uniqueness.
 *
 * <p>Examples:
 * <pre>{@code
 * // ALLOW rule
 * Rule allowRule = Rule.allow()
 *     .withUsername("alice")
 *     .withWorkspace("topp")
 *     .withPriority(100);
 *
 * // DENY rule
 * Rule denyRule = Rule.deny()
 *     .withUsername("bob")
 *     .withWorkspace("topp")
 *     .withLayer("classified")
 *     .withPriority(50);
 * }</pre>
 *
 * <p>Immutable. Use {@code with*()} methods or {@code toBuilder()} for modifications.
 *
 * @param id unique internal identifier for this rule, generated by the repository on rule
 *     creation. {@code null} for transient (unsaved) rules.
 * @param extId external identifier for integration with other systems. Allows external systems to
 *     reference rules using their own identifier schemes, simplifying integration in complex
 *     environments where rules may be managed across multiple systems.
 * @param name human-readable name for the rule. Optional.
 * @param description description explaining the purpose of this rule. Optional.
 * @param priority priority determines evaluation order (lower values = higher priority). Rules are
 *     evaluated in strict priority order; the first rule matching all request criteria determines
 *     the access decision. Priority must be unique across all rules.
 * @param identifier rule matching criteria and access grant type. Defines which requests this rule
 *     applies to (username, role, IP, service, workspace, layer) and what access it grants (ALLOW,
 *     DENY, or LIMIT).
 * @param ruleLimits optional restrictions for LIMIT grant type rules. Only applicable when
 *     {@code identifier.access()} is {@link GrantType#LIMIT}; specifies spatial constraints and
 *     catalog visibility mode.
 * @since 1.0
 * @see RuleIdentifier
 * @see GrantType
 * @see RuleLimits
 * @see LayerDetails
 */
@With
@Builder(toBuilder = true, builderClassName = "Builder")
public record Rule(
        @Nullable String id,
        @Nullable String extId,
        @Nullable String name,
        @Nullable String description,
        long priority,
        RuleIdentifier identifier,
        @Nullable RuleLimits ruleLimits) {

    private static final RuleIdentifier EMPTY_IDENTIFIER =
            RuleIdentifier.builder().build();

    public Rule {
        if (identifier == null) identifier = EMPTY_IDENTIFIER;
    }

    @Override
    public String toString() {
        return "Rule[id: %s, %s]".formatted(id, toShortString());
    }

    public GrantType access() {
        return identifier.access();
    }

    public Rule withUsername(String username) {
        return withIdentifier(identifier.withUsername(username));
    }

    public Rule withRolename(String rolename) {
        return withIdentifier(identifier.withRolename(rolename));
    }

    public Rule withService(String service) {
        return withIdentifier(identifier.withService(service));
    }

    public Rule withAddressRange(String addressRange) {
        return withIdentifier(identifier.withAddressRange(addressRange));
    }

    public Rule withRequest(String request) {
        return withIdentifier(identifier.withRequest(request));
    }

    public Rule withSubfield(String subfield) {
        return withIdentifier(identifier.withSubfield(subfield));
    }

    public Rule withWorkspace(String workspace) {
        return withIdentifier(identifier.withWorkspace(workspace));
    }

    public Rule withLayer(String layer) {
        return withIdentifier(identifier.withLayer(layer));
    }

    public Rule withAccess(GrantType access) {
        return withIdentifier(identifier.withAccess(access));
    }

    public static Rule allow() {
        return Rule.builder().build().withAccess(GrantType.ALLOW);
    }

    public static Rule deny() {
        return Rule.builder().build().withAccess(GrantType.DENY);
    }

    public static Rule limit() {
        return Rule.builder().build().withAccess(GrantType.LIMIT);
    }

    public String toShortString() {
        return "priority: %d, %s".formatted(priority, identifier.toShortString());
    }
}
